### ISSUE TITLE
pypi wheel is broken - pip install fails under py 3.6 and 3.7

### ISSUE THREAD

**Issue by mirekphd** [VowpalWabbit/vowpal_wabbit#1872]
To reproduce: pull python:3.6 or python:latest image from Docker Hub, run and execute `pip install vowpalwabbit`. Hint: consider adding this to your test suite.

Error message under Python 3.6:
```
# docker run -it python:3.6 bash
Unable to find image 'python:3.6' locally
3.6: Pulling from library/python
c5e155d5a1d1: Already exists 
221d80d00ae9: Already exists 
4250b3117dca: Already exists 
3b7ca19181b2: Already exists 
425d7b2a5bcc: Already exists 
d7a526a3eca5: Pull complete 
73a96b82cd2c: Pull complete 
63e5b6830bb3: Pull complete 
811d2b8ea37b: Pull complete 
Digest: sha256:b8f33201e729b6713b00f204a4fb1efe2a4d112e11efe0f3c380a76498e5442e
Status: Downloaded newer image for python:3.6
root@c65b21187c16:/# python --version
Python 3.6.8
root@c65b21187c16:/# pip install vowpalwabbit
Collecting vowpalwabbit
  Downloading https://files.pythonhosted.org/packages/56/45/278a8427aa859888b3fb3e3debeea086557df8def22a23561bfe45e1fb03/vowpalwabbit-8.5.0.tar.gz (1.5MB)
     |████████████████████████████████| 1.5MB 5.9MB/s 
Building wheels for collected packages: vowpalwabbit
  Building wheel for vowpalwabbit (setup.py) ... error
  ERROR: Complete output from command /usr/local/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-6sw0d9sg/vowpalwabbit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ahpug4q4 --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/vowpalwabbit
  copying vowpalwabbit/pyvw.py -> build/lib.linux-x86_64-3.6/vowpalwabbit
  copying vowpalwabbit/__init__.py -> build/lib.linux-x86_64-3.6/vowpalwabbit
  copying vowpalwabbit/sklearn_vw.py -> build/lib.linux-x86_64-3.6/vowpalwabbit
  running egg_info
  writing vowpalwabbit.egg-info/PKG-INFO
  writing dependency_links to vowpalwabbit.egg-info/dependency_links.txt
  writing top-level names to vowpalwabbit.egg-info/top_level.txt
  reading manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.dll' under directory 'bin'
  warning: no previously-included files matching '*.o' found anywhere in distribution
  warning: no previously-included files matching '*.exe' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-6sw0d9sg/vowpalwabbit/setup.py", line 209, in <module>
      tests_require=['tox']
    File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-6sw0d9sg/vowpalwabbit/setup.py", line 119, in build_extension
      env['PYTHON_LIBS'] = '-l {}'.format(find_boost())
    File "/tmp/pip-install-6sw0d9sg/vowpalwabbit/setup.py", line 44, in find_boost
      raise Exception('Could not find boost python library')
  Exception: Could not find boost python library
  ----------------------------------------
  ERROR: Failed building wheel for vowpalwabbit
  Running setup.py clean for vowpalwabbit
Failed to build vowpalwabbit
Installing collected packages: vowpalwabbit
  Running setup.py install for vowpalwabbit ... error
    ERROR: Complete output from command /usr/local/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-6sw0d9sg/vowpalwabbit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uuavnx6d/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/vowpalwabbit
    copying vowpalwabbit/pyvw.py -> build/lib.linux-x86_64-3.6/vowpalwabbit
    copying vowpalwabbit/__init__.py -> build/lib.linux-x86_64-3.6/vowpalwabbit
    copying vowpalwabbit/sklearn_vw.py -> build/lib.linux-x86_64-3.6/vowpalwabbit
    running egg_info
    creating vowpalwabbit.egg-info
    writing vowpalwabbit.egg-info/PKG-INFO
    writing dependency_links to vowpalwabbit.egg-info/dependency_links.txt
    writing top-level names to vowpalwabbit.egg-info/top_level.txt
    writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    reading manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*' under directory 'src'
    warning: no files found matching '*.dll' under directory 'bin'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.exe' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    running build_ext
    make: *** No rule to make target 'clean'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6sw0d9sg/vowpalwabbit/setup.py", line 209, in <module>
        tests_require=['tox']
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-install-6sw0d9sg/vowpalwabbit/setup.py", line 103, in build_extension
        prep()
      File "/tmp/pip-install-6sw0d9sg/vowpalwabbit/setup.py", line 63, in prep
        subprocess.check_call(['make', 'clean'], cwd=path.join(here, 'src', 'python'))
      File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'clean']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command "/usr/local/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-6sw0d9sg/vowpalwabbit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uuavnx6d/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-6sw0d9sg/vowpalwabbit/

```

Error message under Python 3.7:
```
# docker run -it python:3.7 bash
Unable to find image 'python:3.7' locally
3.7: Pulling from library/python
Digest: sha256:7c4fba6c00b4c2542f23e7dc2efec53d5af17864793e6807251078dc418a745b
Status: Downloaded newer image for python:3.7
root@24705ab50b9d:/# pip install vowpalwabbit
Collecting vowpalwabbit
  Downloading https://files.pythonhosted.org/packages/56/45/278a8427aa859888b3fb3e3debeea086557df8def22a23561bfe45e1fb03/vowpalwabbit-8.5.0.tar.gz (1.5MB)
     |████████████████████████████████| 1.5MB 6.7MB/s 
Building wheels for collected packages: vowpalwabbit
  Building wheel for vowpalwabbit (setup.py) ... error
  ERROR: Complete output from command /usr/local/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-08l3ecr_/vowpalwabbit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-v2vy8ax9 --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/vowpalwabbit
  copying vowpalwabbit/pyvw.py -> build/lib.linux-x86_64-3.7/vowpalwabbit
  copying vowpalwabbit/__init__.py -> build/lib.linux-x86_64-3.7/vowpalwabbit
  copying vowpalwabbit/sklearn_vw.py -> build/lib.linux-x86_64-3.7/vowpalwabbit
  running egg_info
  writing vowpalwabbit.egg-info/PKG-INFO
  writing dependency_links to vowpalwabbit.egg-info/dependency_links.txt
  writing top-level names to vowpalwabbit.egg-info/top_level.txt
  reading manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.dll' under directory 'bin'
  warning: no previously-included files matching '*.o' found anywhere in distribution
  warning: no previously-included files matching '*.exe' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-08l3ecr_/vowpalwabbit/setup.py", line 209, in <module>
      tests_require=['tox']
    File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-08l3ecr_/vowpalwabbit/setup.py", line 119, in build_extension
      env['PYTHON_LIBS'] = '-l {}'.format(find_boost())
    File "/tmp/pip-install-08l3ecr_/vowpalwabbit/setup.py", line 44, in find_boost
      raise Exception('Could not find boost python library')
  Exception: Could not find boost python library
  ----------------------------------------
  ERROR: Failed building wheel for vowpalwabbit
  Running setup.py clean for vowpalwabbit
Failed to build vowpalwabbit
Installing collected packages: vowpalwabbit
  Running setup.py install for vowpalwabbit ... error
    ERROR: Complete output from command /usr/local/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-08l3ecr_/vowpalwabbit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xmz67lj8/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/vowpalwabbit
    copying vowpalwabbit/pyvw.py -> build/lib.linux-x86_64-3.7/vowpalwabbit
    copying vowpalwabbit/__init__.py -> build/lib.linux-x86_64-3.7/vowpalwabbit
    copying vowpalwabbit/sklearn_vw.py -> build/lib.linux-x86_64-3.7/vowpalwabbit
    running egg_info
    creating vowpalwabbit.egg-info
    writing vowpalwabbit.egg-info/PKG-INFO
    writing dependency_links to vowpalwabbit.egg-info/dependency_links.txt
    writing top-level names to vowpalwabbit.egg-info/top_level.txt
    writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    reading manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*' under directory 'src'
    warning: no files found matching '*.dll' under directory 'bin'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.exe' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    running build_ext
    make: *** No rule to make target 'clean'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-08l3ecr_/vowpalwabbit/setup.py", line 209, in <module>
        tests_require=['tox']
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-install-08l3ecr_/vowpalwabbit/setup.py", line 103, in build_extension
        prep()
      File "/tmp/pip-install-08l3ecr_/vowpalwabbit/setup.py", line 63, in prep
        subprocess.check_call(['make', 'clean'], cwd=path.join(here, 'src', 'python'))
      File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'clean']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command "/usr/local/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-08l3ecr_/vowpalwabbit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xmz67lj8/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-08l3ecr_/vowpalwabbit/


```

**Comment by peterychang** [comment]
It looks like you don't have boost_python installed. Can you try installing it before running pip?
Be aware that boost_python only installs binaries for python2.7 and one version of python3, depending on the version of boost

**Comment by peterychang** [comment]
If errors persist after installing all VW dependencies, please re-open this issue.
