### ISSUE TITLE
Can't install Vowpalwabbit using pip on Windows 10

### ISSUE THREAD

**Issue by mikgor** [VowpalWabbit/vowpal_wabbit#1893]
I have python 3.7.0 installed on Windows 10 and I can't install VowpalWabbit. When I use command:
`pip install vowpalwabbit`
I get:
```
Collecting vowpalwabbit
  Using cached https://files.pythonhosted.org/packages/56/45/278a8427aa859888b3fb3e3debeea086557df8def22a23561bfe45e1fb03/vowpalwabbit-8.5.0.tar.gz
Building wheels for collected packages: vowpalwabbit
  Building wheel for vowpalwabbit (setup.py) ... error
  ERROR: Complete output from command 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-0tp3npd1\\vowpalwabbit\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\User\AppData\Local\Temp\pip-wheel-78e8xolx' --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  creating build\lib.win32-3.7\vowpalwabbit
  copying vowpalwabbit\pyvw.py -> build\lib.win32-3.7\vowpalwabbit
  copying vowpalwabbit\sklearn_vw.py -> build\lib.win32-3.7\vowpalwabbit
  copying vowpalwabbit\__init__.py -> build\lib.win32-3.7\vowpalwabbit
  running egg_info
  writing vowpalwabbit.egg-info\PKG-INFO
  writing dependency_links to vowpalwabbit.egg-info\dependency_links.txt
  writing top-level names to vowpalwabbit.egg-info\top_level.txt
  reading manifest file 'vowpalwabbit.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.dll' under directory 'bin'
  warning: no previously-included files matching '*.o' found anywhere in distribution
  warning: no previously-included files matching '*.exe' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  writing manifest file 'vowpalwabbit.egg-info\SOURCES.txt'
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\User\AppData\Local\Temp\pip-install-0tp3npd1\vowpalwabbit\setup.py", line 209, in <module>
      tests_require=['tox']
    File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\wheel\bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
      _build_ext.run(self)
    File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "c:\users\user\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\User\AppData\Local\Temp\pip-install-0tp3npd1\vowpalwabbit\setup.py", line 115, in build_extension
      raise Exception('Pre-built vw/python library for Windows is not supported for this python version')
  Exception: Pre-built vw/python library for Windows is not supported for this python version
  ERROR: Failed building wheel for vowpalwabbit
  Running setup.py clean for vowpalwabbit
Failed to build vowpalwabbit
Installing collected packages: vowpalwabbit
  Running setup.py install for vowpalwabbit ... error
    ERROR: Complete output from command 'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-0tp3npd1\\vowpalwabbit\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-2515t1q8\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\vowpalwabbit
    copying vowpalwabbit\pyvw.py -> build\lib.win32-3.7\vowpalwabbit
    copying vowpalwabbit\sklearn_vw.py -> build\lib.win32-3.7\vowpalwabbit
    copying vowpalwabbit\__init__.py -> build\lib.win32-3.7\vowpalwabbit
    running egg_info
    creating vowpalwabbit.egg-info
    writing vowpalwabbit.egg-info\PKG-INFO
    writing dependency_links to vowpalwabbit.egg-info\dependency_links.txt
    writing top-level names to vowpalwabbit.egg-info\top_level.txt
    writing manifest file 'vowpalwabbit.egg-info\SOURCES.txt'
    reading manifest file 'vowpalwabbit.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*' under directory 'src'
    warning: no files found matching '*.dll' under directory 'bin'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.exe' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    writing manifest file 'vowpalwabbit.egg-info\SOURCES.txt'
    running build_ext
    error: [WinError 2] Nie można odnaleźć określonego pliku
    ----------------------------------------
ERROR: Command "'c:\users\user\appdata\local\programs\python\python37-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-0tp3npd1\\vowpalwabbit\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-2515t1q8\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\User\AppData\Local\Temp\pip-install-0tp3npd1\vowpalwabbit\
```
I've tried use Python 3.5.0 and it still didn't work.

**Comment by jackgerrits** [comment]
The Python package includes C++ that needs to be built from source, and is made a bit difficult because the dependencies need to be present too. We are working on making the Python install experience better, but in the meantime here is how I was able to get your situation working on Windows 10 1809 from latest vw master. (Things have changed quite a bit since 8.5.0 which is what is on pip)

- For Python3.7 I used Boost 1.70 (This is the latest version on vcpkg)
- I used CMake 3.13 and it was able to resolve the Boost 1.70 dependencies

1. [Install vcpkg ](https://github.com/Microsoft/vcpkg)
2. [Install dependencies with vcpkg](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Dependencies#experimental-cmake-build-system-on-windows)
    ```
    vcpkg install zlib:x64-windows
    vcpkg install boost-system:x64-windows
    vcpkg install boost-program-options:x64-windows
    vcpkg install boost-test:x64-windows
    vcpkg install boost-align:x64-windows
    vcpkg install boost-foreach:x64-windows
    vcpkg install boost-python:x64-windows
    vcpkg install boost-math:x64-windows
    vcpkg install boost-thread:x64-windows
    ```
3. ` cd <repo_root>/python`
4. `python setup.py --vcpkg-root C:\path\to\vcpkg install`
    - Where `C:\path\to\vcpkg` is the root directory of where you cloned vcpkg

**Comment by peterychang** [comment]
Updated installation instructions for 64-bit Python 3.6 and 3.7 on Windows:
Binary wheels have been released for these environments. Install using
`pip install vowpalwabbit`

**Comment by HarshKhilawala** [comment]
@jackgerrits  I did the steps as mentioned by you but still unable

**Comment by jackgerrits** [comment]
peterychang provided updated instructions. Did you run `pip install vowpalwabbit`?

**Comment by HarshKhilawala** [comment]
Yes @jackgerrits , I am using Python 3.9. I am also followed your above steps for boost library

**Comment by jackgerrits** [comment]
3.9 is not available as a binary package at the moment. Please see here for the Python support status: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Python#support I'd recommend using Python 3.8 until that is ready

**Comment by HarshKhilawala** [comment]
@jackgerrits Thank you very much! It seems to be installed perfectly
