### ISSUE TITLE
VW JNI install on macOS Big Sur fails

### ISSUE THREAD

**Issue by ramkumarrani** [VowpalWabbit/vowpal_wabbit#3395]
I am trying to deploy VW JNI on MacOS (Big Sur).  First, the JNI build errored with clang issue; referred this article: https://github.com/VowpalWabbit/vowpal_wabbit/issues/2521 and modified CMakeLists.txt.  The else() condition has got this: target_link_libraries(vw_jni PUBLIC -fPIC -Wl,-rpath,\"\$ORIGIN\")

However, when I run the command: make vw_jni, I get following errors:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.044 sec - in vowpalWabbit.learner.VWCCBLearnerTest
Running vowpalWabbit.learner.VWActionScoresLearnerTest
Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.054 sec <<< FAILURE! - in vowpalWabbit.learner.VWActionScoresLearnerTest
testCBADFWithRank(vowpalWabbit.learner.VWActionScoresLearnerTest)  Time elapsed: 0.019 sec  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [1]; expected:<ActionScores{actionScores=[ActionScore{action=0, score=0.11246802}, ActionScore{action=1, score=0.11246802}]}> but was:<ActionScores{actionScores=[ActionScore{action=0, score=0.11246799}, ActionScore{action=1, score=0.11246799}]}>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:50)
	at org.junit.Assert.internalArrayEquals(Assert.java:473)
	at org.junit.Assert.assertArrayEquals(Assert.java:265)
	at org.junit.Assert.assertArrayEquals(Assert.java:280)
	at vowpalWabbit.learner.VWActionScoresLearnerTest.testCBADF(VWActionScoresLearnerTest.java:113)
	at vowpalWabbit.learner.VWActionScoresLearnerTest.testCBADFWithRank(VWActionScoresLearnerTest.java:74)

testCBADF(vowpalWabbit.learner.VWActionScoresLearnerTest)  Time elapsed: 0.006 sec  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [1]; expected:<ActionScores{actionScores=[ActionScore{action=0, score=0.11246802}, ActionScore{action=1, score=0.11246802}]}> but was:<ActionScores{actionScores=[ActionScore{action=0, score=0.11246799}, ActionScore{action=1, score=0.11246799}]}>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:50)
	at org.junit.Assert.internalArrayEquals(Assert.java:473)
	at org.junit.Assert.assertArrayEquals(Assert.java:265)
	at org.junit.Assert.assertArrayEquals(Assert.java:280)
	at vowpalWabbit.learner.VWActionScoresLearnerTest.testCBADF(VWActionScoresLearnerTest.java:113)
	at vowpalWabbit.learner.VWActionScoresLearnerTest.testCBADF(VWActionScoresLearnerTest.java:69)

testCSOAA(vowpalWabbit.learner.VWActionScoresLearnerTest)  Time elapsed: 0.007 sec  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [0]; expected:<ActionScores{actionScores=[ActionScore{action=1, score=-1.0573887}, ActionScore{action=0, score=-0.033036415}, ActionScore{action=2, score=1.0063205}]}> but was:<ActionScores{actionScores=[ActionScore{action=1, score=-1.057399}, ActionScore{action=0, score=-0.033034213}, ActionScore{action=2, score=1.0063031}]}>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:50)
	at org.junit.Assert.internalArrayEquals(Assert.java:473)
	at org.junit.Assert.assertArrayEquals(Assert.java:265)
	at org.junit.Assert.assertArrayEquals(Assert.java:280)
	at vowpalWabbit.learner.VWActionScoresLearnerTest.testCSOAA(VWActionScoresLearnerTest.java:64)

Results :

Failed tests: 
  VWScalarsLearnerTest.probs:48 arrays first differed at element [0]; expected:<0.475999> but was:<0.47602984>
  VWProbLearnerTest.prob:34 arrays first differed at element [1]; expected:<0.38244691> but was:<0.382425>
  VWActionScoresLearnerTest.testCBADFWithRank:74->testCBADF:113 arrays first differed at element [1]; expected:<ActionScores{actionScores=[ActionScore{action=0, score=0.11246802}, ActionScore{action=1, score=0.11246802}]}> but was:<ActionScores{actionScores=[ActionScore{action=0, score=0.11246799}, ActionScore{action=1, score=0.11246799}]}>
  VWActionScoresLearnerTest.testCBADF:69->testCBADF:113 arrays first differed at element [1]; expected:<ActionScores{actionScores=[ActionScore{action=0, score=0.11246802}, ActionScore{action=1, score=0.11246802}]}> but was:<ActionScores{actionScores=[ActionScore{action=0, score=0.11246799}, ActionScore{action=1, score=0.11246799}]}>
  VWActionScoresLearnerTest.testCSOAA:64 arrays first differed at element [0]; expected:<ActionScores{actionScores=[ActionScore{action=1, score=-1.0573887}, ActionScore{action=0, score=-0.033036415}, ActionScore{action=2, score=1.0063205}]}> but was:<ActionScores{actionScores=[ActionScore{action=1, score=-1.057399}, ActionScore{action=0, score=-0.033034213}, ActionScore{action=2, score=1.0063031}]}>

Tests run: 34, Failures: 5, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.092 s
[INFO] Finished at: 2021-10-14T11:12:34-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project vw-jni: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/ramkumar_rani/Vwabbit1/vowpal_wabbit/java/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
make[3]: *** [java/libvw_jni.dylib] Error 1
make[3]: *** Deleting file `java/libvw_jni.dylib'
make[2]: *** [java/CMakeFiles/vw_jni.dir/all] Error 2
make[1]: *** [java/CMakeFiles/vw_jni.dir/rule] Error 2
make: *** [vw_jni] Error 2

==> Issue 2521 (link above) does not suggest a solution. 

==> Please suggest me how to fix this issue.

**Comment by ramkumarrani** [comment]
Hi Jack,

Thanks.  2747 helps.  when built (make vw_jni) is done, the final file it produces is vowpal_wabbit/build/java/libvw_jni.dylib.  How to create libvw_jni.so from here?
