### ISSUE TITLE
ci: test failure intermittent

### ISSUE THREAD

**Issue by lalo** [VowpalWabbit/vowpal_wabbit#3782]
`    Failed TestSharedModel [1 s]

CUSTOMBUILD : error Message:  [D:\a\vowpal_wabbit\vowpal_wabbit\vw\build\test_with_output.vcxproj]
     Test method cs_unittest.TestCbAdfClass.TestSharedModel threw exception: 
  System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
    Stack Trace:
        at VW.finish(workspace* , Boolean )
     at VW.VowpalWabbitBase.InternalDispose() in D:\a\vowpal_wabbit\vowpal_wabbit\vw\cs\cli\vw_base.cpp:line 157
     at VW.VowpalWabbitBase.~VowpalWabbitBase() in D:\a\vowpal_wabbit\vowpal_wabbit\vw\cs\cli\vw_base.cpp:line 94
     at VW.VowpalWabbitBase.Dispose(Boolean A_0) in C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\sstream:line 0
     at VW.VowpalWabbitBase.Dispose()
     at VW.VowpalWabbit`2.Dispose(Boolean disposing) in D:\a\vowpal_wabbit\vowpal_wabbit\vw\cs\cs\VowpalWabbit.cs:line 506
     at VW.VowpalWabbit`2.Dispose() in D:\a\vowpal_wabbit\vowpal_wabbit\vw\cs\cs\VowpalWabbit.cs:line 496
     at cs_unittest.TestCbAdfClass.TestSharedModel() in D:\a\vowpal_wabbit\vowpal_wabbit\vw\cs\unittest\TestCbAdf.cs:line 166
  `

see https://github.com/VowpalWabbit/vowpal_wabbit/runs/5469418230?check_suite_focus=true

I've only seen this on "Windows / C++ - CMake only" CI

**Comment by JohnLangford** [comment]
Fixed in #4838
